# [#1969](https://github.com/tc39/ecma262/pull/1969/files): Editorial: Return an iterator *record* for for...in heads [Reference Error]

- **Version**: [0e83cd040fe1f374fb472f946587d942829e755a](https://github.com/tc39/ecma262/commits/0e83cd040fe1f374fb472f946587d942829e755a)
  - **Type**: Reference Error
  - **Algorithm**: `ForIn/OfHeadEvaluation`
  - **Description**: `ForIn/OfHeadEvaluation` 은 `Iterator Record` 를 반환해야 하지만, `Iterator Object` 를 반환하는 경우가 발생했음. 이는 결국 `ForIn/OfBodyEvaluation` 의 `iteratorRecord` 로 흘러가는데, 이후 `iteratorRecord` 의 field 에 접근할 때, reference error 가 나와야함
  - **Count**: 9
    - 13.7.5.11 Runtime Semantics: LabelledEvaluation 에서 `IterationStatement`의 9가지 production에 대해서 각각 다른 View를 가지고 `ForInOfBodyEvaluaiton`을 부를 때, `keyResult`라는 함수 argument에 `ForInOfHeadEvaluaiton`의 잘못된 결과가 전달됨. 
  - **Alarms**
  - **Status**
    - 언급한대로 `ForInOfBodyEvaluation`에서 `iteratorRecord`가 `Object`로 잘못 전달된채로 분석이 진행되는데,
      `app __x1__ = (Call iteratorRecord.NextMethod iteratorRecord.Iterator)` statement에서 property access를 할 때 alarm이 발생하지 않음.
      해당 statement에서 `iteratorRecord.NextMethod`를 transfer할 때 Reference Error가 발생해야 함.
    - 참고 : AbsState.scala:87 - `TODO if (check && t.isMustAbsent) alarm(s"unknown property: $base.$prop")`

